
name: Disability Benefits Team Issue Template
description: Issues for Disability Benefits Team 
labels: ["disability", "disability-benefits", "needs-refinement"]
projects: 
- department-of-veterans-affairs/1660

body:
- type: textarea
  attributes:
    label: Value Statement 
    description: Describe the story
    placeholder: |
      (As a) user type 
      (I want to) job to be done 
      (So that) desired outcome(s) 
- type: textarea
  attributes:
    label: Background Context
    description: What's the context?
    placeholder: Add here
- type: textarea
  attributes:
    label: Tasks
    description: What are the tasks for this work?
    placeholder: |
      - Task
      - Task
      - Task
- type: textarea
  attributes:
    label: Dependencies
    description: What's things is this work dependent on?
    placeholder: Add here
- type: textarea
  attributes:
    label: Out of scope
    description: What's things are NOT in scope for this work?
    placeholder: Add here

- type: textarea
  attributes:
    label: Open questions
    description: Are there any open questions?
    placeholder: Add here

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: What is the acceptable conditions to consider this work complete?
    placeholder: |
      - AC
      - AC
      - AC
- type: textarea
  attributes:
    label: Outcome, Success Measure, KPI(S), and Tracking Link
    description: Measuring success of this work
    placeholder: Add here

- type: checkboxes
  attributes: 
    label: Definition of Done
    description: Describe here
    options:
      - label: Meets acceptance criteria
      - label: Passed all testing coverage
      - label: Code or content reviewed (Internal)
      - label: Reviewed and approved by product and/or design
    
