name: Identity Engineer Support
description: For requesting engineering help from the identity team
labels: 'identity-engineer-support'
body:
  - type: textarea
    attributes:
      label: Issue Description
      description: Describe the issue details
      placeholder: Insert issue details here
  - type: markdown
    attributes:
      value: >
        This is a GitHub issue template for users and teams who need engineering
        support services from the
        [Identity](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity)
        team such as authentication help, PR reviews, SiS setup and support, or
        technical questions. Please provide the information needed for the issue
        type you are requesting support for. For “other” please provide
        additional details. For large data requests, SiS information and
        onboarding, or new projects please use [this
        template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=Identity%2C+Identity+Product+Support&projects=&template=1dentity-product-support.yaml).


        ### **To properly assist with your issue, please complete the
        following:**


        - [ ] **Complete this issue template**

        - [ ] **Provide your name and email address**

        - [ ] **Provide your team’s name**

        - [ ] **Select issue type (for “other” stop here and provide details)**

        - **Authentication Help**

        - **Pull Request Review**

        - **Technical Questions**

        - **Other**

        - [ ] **Complete tasks for your issue type**

        - [ ] **Add additional details (optional)**

        - [ ] **Complete the [post Identity team support
        survey](https://dj540s05.optimalworkshop.com/questions/52low0ey) before
        closing this ticket**
            

        **Name:**


        **Email address:**


        **Team Name:**


        **Issue Type:**


        **Additional Details:**


        ## **Authentication Help Request**


        - **Review [troubleshooting
        documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Troubleshooting_logging/troubleshooting_signin.md)**


        **Provide Additional Details below**


        - Which Environment did you use to sign in?
          - Local Host
          - Development
          - Review
          - Staging
          - Production
        - Which user email did you use to sign in?

        - Which Credential Service Provider (CSP) did you use?
          - Login.gov
          - ID.me
          - DSLogon
          - My HealthVet
        - Can you provide a screenshot of the error page? Include the screenshot
        of the DevTools console. (optional)

        - Include and error codes you see. (optional)

        - Include any relevant timestamps you see. (optional)

        - Include the failed request ID if you have access to it. (optional)

        - Have you tried clearing your browser cache?

        - Have you tried clearing your browser cookies?

        - Have you tried signing in incognito?

        - Which browser(s) did you try to sign in with?
          - Chrome
          - Safari
          - Firefox
          - MS Edge
          - VA Mobile iOS
          - VA Mobile Android
          - Other

        ## **Pull review request**


        - **Provide additional informational Information below**

        - Please provide a URL to link to your PR:

        - Have you tested your changes?


        ## **Technical Questions**


        - Join one of our [office hours]() meetings on Thursdays to meet with an
        engineer directly

        - Ask your question here in this template and an engineer will respond


        ## **Additional information**


        - The identity team maintains [office
        hours](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Support%20Documents/office-hours.md)
        for both frontend and backend engineers.

        - You may reach out to an identity team member on the
        ```#vsp-identity``` [slack
        channel](https://dsva.slack.com/archives/CSFV4QTKN) on the Office of the
        CTO @ va slack workspace.

        - Please review the ```#vsp-identity``` slack channel [canvas] to
        reference information about the identity team.
