name: "Identity Product Support"
description: "For general Identity support request"
labels: "Identity, identity-product-support"
assignees: jimcconnelly, kingbmike
body:
- type: markdown
  attributes:
    value: |
      # Identity Product Support Request

      This is a GitHub issue template for users and teams who need product support services from the [Identity team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity). Please provide the information needed for the issue type you are requesting support for. For “other” please provide additional details. You may view Identity teams documentation for all of our products and services [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products). For engineering support, use our [engineer issue template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joeniquette&labels=Identity%2C+identity-engineer-support&projects=&template=1dentity-engineer-support.md&title=) instead.

      ### To properly assist with your issue, please complete the following:

      - [ ] Complete this issue template
      - [ ] Provide your name and email address
      - [ ] Provide your team’s name
      - [ ] Select issue type (for “other” stop here and provide details)
        - Sign-In-Service Integration
        - Data Request
        - Other
      - [ ] Complete tasks for your issue type
      - [ ] Add additional details (optional)
      - [ ] Complete the [post Identity team support survey](https://dj540s05.optimalworkshop.com/questions/52low0ey) before closing this ticket
- type: input
  id: name
  attributes:
    label: Provide your name
- type: input
  id: email
  attributes:
    label: Provide your email address
  validations:
    required: true
- type: input
  id: team_name
  attributes:
    label: Provide your team’s name
- type: dropdown
  id: issue_type
  attributes:
    label: Select issue type (for "other" stop here and provide details)
    options:
      - Select an issue type
      - Data Request
      - Sign-in Service Integration
      - Other
    multiple: false
    default: 0
  validations:
    required: true
- type: textarea
  id: details
  attributes:
    label: Provide additional details about your issue
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ---
      <details><summary><h2>Data Request</h2></summary>
- type: textarea
  id: data_request
  attributes:
    label: Provide additional details below
    description: |
      - What data do you need pulled? Please don’t include any Personal Identifying Information (PII)
      - Is this sensitive data that requires special permissions?
- type: markdown
  attributes:
    value: |
      </details>
- type: markdown
  attributes:
    value: |
      ---
      ## **Sign-in Service**

      We maintain a [Sign-in Service overview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service) as well as [engineering documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs) in the va-gov-team GitHub repository. To begin onboarding or register a Client or Service Configuration, continue reading.

      ### **Begin Onboarding**

      - **Provide the first and last name of the primary point of contact**
      - **Provide an email address for the primary point of contact**
- type: markdown
  attributes:
    value: |
      ### **Onboarding Questionnaire**
- type: dropdown
  id: sis_onboarding_1
  attributes:
    description: |
      - If end users interact with your application, you will most likely need to [configure your integration as a client application](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/configuration/client_config.md).
      - If end users don’t interact with your application, your integration will likely need to be [configured as a service account]() [configured as a service account](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/configuration/service_account.md).
    label: "Does your application interact with end users, API’s or both?"
    options:
      - Interact with end users only
      - Interact with APIs only
      - Interact with both
- type: dropdown
  id: sis_onboarding_2
  attributes:
    description: |
      Read more about the [Unified Sign-in Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Unified%20Sign%20In%20Pages/README.md)
    label: Do you need to use our Unified Sign-in Page (USiP)?
    options:
      - "Yes, I will need integration with the Unified Sign-in Page"
      - "No, I do not need integration with the Unified Sign-in Page"
- type: dropdown
  id: sis_onboarding_3
  attributes:
    description: |
      - If "Yes", your application will need [cookie-based authentication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/auth_flows/cookie_oauth.md).
      - If "No", your application will need to [authenticate via API](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/auth_flows/api_oauth.md).
    label: If your application is used by end users, is it used in a web browser?
    options:
      - "Yes, my application uses a web browser"
      - "No, my application does not use a web browser"
- type: dropdown
  id: sis_onboarding_4
  attributes:
    description: |
      - If "Frontend" reference the appropriate authentication guide in Step #3 and complete the step for PKCE authentication.
      - If "Backend", reference the authentication guide, but register a public certificate for [private key JWT authentication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/auth_flows/private_key_jwt.md).
    label: Is your authentication facilitated by a frontend or a secure backend?
    options:
      - Frontend (PKCE)
      - Backend (Private Key JWT)
- type: markdown
  attributes:
    value: |
      ---
      ### Client Configuration
- type: dropdown
  id: client_config_1
  attributes:
    label: Is the application used in a web browser?
    options:
      - "Yes, the application is used in a web browser or mobile app"
      - "No, the application is not used in a web browser or mobile app"
- type: dropdown
  id: client_config_2
  attributes:
    description: |
      Read more about the [Unified Sign-in Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Unified%20Sign%20In%20Pages/README.md)
    label: Will your application be using our Unified Sign-in Page (USiP)?
    options:
      - "Yes, I will need integration with the Unified Sign-in Page"
      - "No, I do not need integration with the Unified Sign-in Page"
- type: textarea
  id: client_config_3
  attributes:
    label: Briefly describe your application (Client Configuration)
- type: markdown
  attributes:
    value: |
      ---
      ### Service Configuration
- type: textarea
  id: service_config_1
  attributes:
    label: Briefly describe your application (Service Configuration)
- type: textarea
  id: service_config_2
  attributes:
    label: Provide additional details to describe your request (optional)
- type: markdown
  attributes:
    value: |
      ## **Additional information**

      - The identity team maintains [office hours](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service/Support) for both frontend and backend engineers.
      - You may reach out to an identity team member on the `#vsp-identity` [slack channel](https://dsva.slack.com/archives/CSFV4QTKN) on the Office of the CTO @ va slack workspace.
      - Please review the `#vsp-identity` slack channel [canvas] to reference information about the identity team.
