name: "Analytics - VFS Custom Event Audit Form" 
about: "This for is for VFS teams to audit the list of custom events for each of their products." 
title: "VFS Custom Events for [Team Name]"
labels: "analytics-insights, analytics-request, ga4-migration, analytics-insights-form"
assignees: johnny-jesensky-adhoc
body:
- type: markdown
  attributes:
    value: "# (WIP) VFS Custom Event Form" 
 - type: markdown
    attributes:
      value: "## What this form is for"
 - type: markdown
    attributes:
      value: |
      "In prepration for the migration to GA4 we need information from your teams to ensure that data is transfered properly..."
 - type: markdown
    attributes:
      value: "## Instructions"
 - type: markdown
    attributes:
      value: "- **Make a copy of this spreadsheet ____**|- **Fill out all sections** |- **Example** (add images)"
 - type: markdown
    attributes:
      value: "### Please provide the following details for this form" 
 - type: markdown
    attributes:
      value: "- **Team Name** | - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]"
 - type: markdown
    attributes:
      value: " **Poduct Name** | - [Insert product name(s) from this [directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)]"
