name: Disability Benefits Team Issue Template test
description: Issues for Disability Benefits Team 
labels: ["disability", "disability-benefits", "needs-refinement"]
projects: 
- department-of-veterans-affairs/1660

body:
- type: textarea
  attributes:
    label: User Need 
    description: |
      As a **user** // I want to **do something** // so that **something happens**
    placeholder: |
      As a **user** // I want to **do something** // so that **something happens**
- type: textarea
  attributes:
    label: Description
    description: Describe the goal or outcome of this work, background context, why it matters, dependencies, and open questions.
- type: textarea
  attributes:
    label: Tasks
    description: What are the tasks for this work?
    placeholder: |
      - [ ] Task
      - [ ] Task
      - [ ] Task
- type: textarea
  attributes:
    label: Acceptance Criteria 
    description: What are the acceptable conditions to consider this work complete? 
    placeholder: |
      - [ ] AC
      - [ ] AC
      - [ ] AC
- type: checkboxes
  attributes: 
    label: Definition of Done
    options:
      - label: Meets acceptance criteria
      - label: Passed all testing coverage
      - label: Code or content reviewed (Internal)
      - label: Reviewed and approved by product and/or design

- type: checkboxes
  attributes:
    label: Refinement Checklist! 
    description: Make this ticket ready to work
    options: 
      - label: Add description, tasks, and acceptance criteria
      - label: Add estimation
      - label: Add the proper labels, team, and priority
      - label: Add an Epic
    
