name: Disability Benefits - Content Support Request Template
description: Content support request for the Disability Benefits Crew
title: "[INTAKE] Team name: Initiative name"
labels: ["disability", "disability-benefits", "content"]
projects:
- department-of-veterans-affairs/1660
type: Task
assignees: amylago

body:
- type: markdown
  attributes:
    value: |
      **Ask the Disability Benefits Crew (DBC) content designer for support. Use clear, simple language to describe the work.**

- type: textarea
  attributes:
    label: Description
    description: Describe the scope of this work, background context, why it matters, dependencies, goals, and open questions.
  validations:
    required: true
- type: textarea
  attributes:
    label: Tasks
    description: What are the tasks for this work?
  validations:
    required: true
- type: textarea
  attributes:
    label: Acceptance Criteria
    description: What are the acceptable conditions to consider this work complete?

- type: checkboxes
  attributes:
    label: Which of these descriptions best fits the work we'll partner on? (select all that apply)
    options:
      - label: Digitizing a new form
      - label: Updating an existing form
      - label: Incorporating C&IA content feedback
      - label: Something else:
      
- type: textarea
  attributes:
    label: Enter
    description: Enter here

- type: input
  attributes:
    label: Figma file
  validations:
    required: true
- type: input
  attributes:
    label: Mural 
- type: input
  attributes:
    label: Relevant research or insights
    description: Provide links to any relevant research findings or usability insights.
- type: textarea
  attributes:
    label: Technical constraints
    description: Describe any technical considerations or limitations.

- type: checkboxes
  attributes:
    label: Definition of Done
    options:
      - label: Issue reviewed with the content designer during content support office hours or a separate sync 
      - label: Acceptance criteria met
      - label: Content reviewed and approved by product and/or design
      - label: VA design lead consulted to determine if a review by the C&IA team is required
      - label: C&IA intake ticket created if content requires review


