---
name: MHV Accessibility Intake Ticket
description: Please use this form to request support from MHV Accessibility
title: "[MHV [Product] / Accessibility] [service type] [brief description]"
labels:
  - accessibility
  - mhv-accessibility
  - mhv-accessibility-intake
assignees:
  - steveg-IAT
  - sarahhortonadhoc
projects:
  - department-of-veterans-affairs/1898
type: epic
body:
  - type: markdown
    attributes:
      value: "# MHV Accessibility Intake Ticket"
  - type: markdown
    attributes:
      value: >
        > [!TIP] > Use the following format for the ticket title — [MHV [Product
        > Appts | MR | Meds | SM | Portal] / Accessibility] [service type] [brief description]
  - type: markdown
    attributes:
      value: |
        ## Request Description
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Provide a short summary of what support is needed.
  - type: textarea
    id: background
    attributes:
      label: 📝 Background and context
      description: Describe the background and context for the work, for example, problem statement, teams involved, approach, goals, and objectives, desired outcomes.
  - type: markdown
    attributes:
      value: |
        ## Request Details
  - type: input
    id: contact
    attributes:
      label: ✋ Point of contact
      description: Provide the name and username of the person who will be
        coordinating the work.
    validations:
      required: true
  - type: input
    id: product
    attributes:
      label: 🛠️ Product
      description: Provide the name of the MHV product. Be sure to add the product's
        project and labels to ticket.
  - type: input
    id: slack
    attributes:
      label: 🗣️ Slack channel
      description: Link to the Slack channel for discussions about this work.
  - type: textarea
    id: timeframe
    attributes:
      label: ⏳ Timeframe
      description: Provide details about the timeframe for this work, for example, staging review dates.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### ✅ Type of support
  - type: checkboxes
    id: evaluation
    attributes:
      label: Evaluation Support
      options:
        - label: Design review — Review design artifacts to identify accessibility issues
            and recommend solutions.
        - label: Conformance testing — Perform an accessibility audit of a functional user
            flow to identify accessibility issues and recommend solutions.
        - label: Accessibility artifact— Prepare an accessibility artifact for a
            Collaboration Cycle review and identify issues and recommend
            solutions.
  - type: checkboxes
    id: research
    attributes:
      label: Research Support
      options:
        - label: Planning — Review research artifacts, run through conversation guide, and
            recommend improvements.
        - label: Observation — Participate in research sessions and provide observation
            notes and takeaways.
  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Support
      options:
        - label: Design — Prepare accessible designs, collaborate on design tasks and
            resolving tickets, etc.
        - label: Engineering — Prepare accessible prototypes, collaborate on engineering
            tasks and resolving tickets, etc.
  - type: checkboxes
    id: general
    attributes:
      label: General Support
      options:
        - label: Issue review — Review tickets or other reports of accessibility issues
            and provide guidance on how to address issues.
        - label: Consulting — Provide general guidance and training on accessibility
            topics.
  - type: textarea
    id: related
    attributes:
      label: 🔗 Related issues
      description: List and link to tickets that are related to this support request.
  - type: textarea
    id: supporting
    attributes:
      label: 🔗 Supporting resources
      description: Share links to supporting design artifacts, prototypes, research
        artifacts, or other details related to this support request.
  - type: textarea
    id: additional
    attributes:
      label: ➕ Additional details
      description: Share any additional details about this support request, e.g.,
        urgency and timeframe, goals and desired outcomes.
  - type: markdown
    attributes:
      value: |
        ## Next Steps
  - type: checkboxes
    id: next
    attributes:
      label: ✅ Next steps
      options:
        - label: Add ticket labels — Add the product's project and labels.
        - label: Save and submit — Save and submit this intake ticket.
        - label: Share on Slack — Start a new thread and post a link to this ticket in the
            mhv-accessibility Slack channel
